<?php
$fruites1 = [
    'apple',
    'pear',
    'orange',
    'banana',
    'kiwi',
    'pomogranate',
    'strawberry',
    'lime',
    'lemon',
    'blueberry',
    'rawberry',
    'grapes',
    'coconuts',
    'pineapples',
    'watermelon',
    'melon',
    'mandarin',
    'peach',
    'plum',
    'cherry',
    'blackerry',
    'apricot',
    'dragon fruits',
    'dades',
    'mango',
    'fig',
    'mallberry',
    'papaya',
    'grapefruites',
    'guava',
    'starfruite',
    'crunberry',
    'rose hip',
];
$fruites2 = [
    'apple',
    'pear',
    'orange',
    'banana',
    'kiwi',
    'pomogranate',
    'strawberry',
    'lime',
    'lemon',
    'blueberry',
    'rawberry',
    'grapes',
    'coconuts',
    'pineapples',
    'watermelon',
    'melon',
    'mandarin',
    'peach',
    'plum',
    'cherry',
    'blackerry',
    'apricot',
    'dragon fruits',
    'dades',
    'mango',
    'fig',
    'mallberry',
    'papaya',
    'grapefruites',
    'guava',
    'starfruite',
    'crunberry',
    'rose hip',
];
$fruites3 = [
    'apple',
    'pear',
    'orange',
    'banana',
    'kiwi',
    'pomogranate',
    'strawberry',
    'lime',
    'lemon',
    'blueberry',
    'rawberry',
    'grapes',
    'coconuts',
    'pineapples',
    'watermelon',
    'melon',
    'mandarin',
    'peach',
    'plum',
    'cherry',
    'blackerry',
    'apricot',
    'dragon fruits',
    'dades',
    'mango',
    'fig',
    'mallberry',
    'papaya',
    'grapefruites',
    'guava',
    'starfruite',
    'crunberry',
    'rose hip',
];
$fruites4 = [
    'apple',
    'pear',
    'orange',
    'banana',
    'kiwi',
    'pomogranate',
    'strawberry',
    'lime',
    'lemon',
    'blueberry',
    'rawberry',
    'grapes',
    'coconuts',
    'pineapples',
    'watermelon',
    'melon',
    'mandarin',
    'peach',
    'plum',
    'cherry',
    'blackerry',
    'apricot',
    'dragon fruits',
    'dades',
    'mango',
    'fig',
    'mallberry',
    'papaya',
    'grapefruites',
    'guava',
    'starfruite',
    'crunberry',
    'rose hip',
];
$fruites5 = [
    'apple',
    'pear',
    'orange',
    'banana',
    'kiwi',
    'pomogranate',
    'strawberry',
    'lime',
    'lemon',
    'blueberry',
    'rawberry',
    'grapes',
    'coconuts',
    'pineapples',
    'watermelon',
    'melon',
    'mandarin',
    'peach',
    'plum',
    'cherry',
    'blackerry',
    'apricot',
    'dragon fruits',
    'dades',
    'mango',
    'fig',
    'mallberry',
    'papaya',
    'grapefruites',
    'guava',
    'starfruite',
    'crunberry',
    'rose hip',
];
$fruites6 = [
    'apple',
    'pear',
    'orange',
    'banana',
    'kiwi',
    'pomogranate',
    'strawberry',
    'lime',
    'lemon',
    'blueberry',
    'rawberry',
    'grapes',
    'coconuts',
    'pineapples',
    'watermelon',
    'melon',
    'mandarin',
    'peach',
    'plum',
    'cherry',
    'blackerry',
    'apricot',
    'dragon fruits',
    'dades',
    'mango',
    'fig',
    'mallberry',
    'papaya',
    'grapefruites',
    'guava',
    'starfruite',
    'crunberry',
    'rose hip',
];
$fruites7 = [
    'apple',
    'pear',
    'orange',
    'banana',
    'kiwi',
    'pomogranate',
    'strawberry',
    'lime',
    'lemon',
    'blueberry',
    'rawberry',
    'grapes',
    'coconuts',
    'pineapples',
    'watermelon',
    'melon',
    'mandarin',
    'peach',
    'plum',
    'cherry',
    'blackerry',
    'apricot',
    'dragon fruits',
    'dades',
    'mango',
    'fig',
    'mallberry',
    'papaya',
    'grapefruites',
    'guava',
    'starfruite',
    'crunberry',
    'rose hip',
];
$fruites8 = [
    'apple',
    'pear',
    'orange',
    'banana',
    'kiwi',
    'pomogranate',
    'strawberry',
    'lime',
    'lemon',
    'blueberry',
    'rawberry',
    'grapes',
    'coconuts',
    'pineapples',
    'watermelon',
    'melon',
    'mandarin',
    'peach',
    'plum',
    'cherry',
    'blackerry',
    'apricot',
    'dragon fruits',
    'dades',
    'mango',
    'fig',
    'mallberry',
    'papaya',
    'grapefruites',
    'guava',
    'starfruite',
    'crunberry',
    'rose hip',
];
$fruites9 = [
    'apple',
    'pear',
    'orange',
    'banana',
    'kiwi',
    'pomogranate',
    'strawberry',
    'lime',
    'lemon',
    'blueberry',
    'rawberry',
    'grapes',
    'coconuts',
    'pineapples',
    'watermelon',
    'melon',
    'mandarin',
    'peach',
    'plum',
    'cherry',
    'blackerry',
    'apricot',
    'dragon fruits',
    'dades',
    'mango',
    'fig',
    'mallberry',
    'papaya',
    'grapefruites',
    'guava',
    'starfruite',
    'crunberry',
    'rose hip',
];
$fruites10 = [
    'apple',
    'pear',
    'orange',
    'banana',
    'kiwi',
    'pomogranate',
    'strawberry',
    'lime',
    'lemon',
    'blueberry',
    'rawberry',
    'grapes',
    'coconuts',
    'pineapples',
    'watermelon',
    'melon',
    'mandarin',
    'peach',
    'plum',
    'cherry',
    'blackerry',
    'apricot',
    'dragon fruits',
    'dades',
    'mango',
    'fig',
    'mallberry',
    'papaya',
    'grapefruites',
    'guava',
    'starfruite',
    'crunberry',
    'rose hip',
];
$fruites = array_merge(
    $fruites1,
    $fruites2,
    $fruites3,
    $fruites4,
    $fruites5,
    $fruites6,
    $fruites7,
    $fruites8,
    $fruites9,
    $fruites10
);


foreach ($fruites as $count => $fruite) {
    if ($fruite == 'apple') {
        echo "<img class='fruites' src='https://www.shareicon.net/data/256x256/2015/05/08/35268_apple_400x400.png'>";
    } else if ($fruite == 'orange') {
        echo "<img class='fruites' src='https://i.pinimg.com/originals/be/a9/23/bea92351105c6cb7d8cf8ef3ccdf2962.png'>";
    } else if ($fruite == 'banana') {
        echo "<img class='fruites' src='https://vignette.wikia.nocookie.net/feed-your-pets-roblox/images/6/69/Banana.png/revision/latest?cb=20180503075351'>";
    } else if ($fruite == 'pear') {
        echo "<img class='fruites' src='https://kopparberg.co.uk/wp-content/uploads/2018/04/Pear.png'>";
    }
}


echo "<hr>";

for ($i=0; $i<count($fruites); $i++) {
    echo $i.': ';

    if ($fruites[$i] == 'apple') {
        echo "<img class='fruites' src='https://www.shareicon.net/data/256x256/2015/05/08/35268_apple_400x400.png'>";
    } else if ($fruites[$i] == 'orange') {
        echo "<img class='fruites' src='https://i.pinimg.com/originals/be/a9/23/bea92351105c6cb7d8cf8ef3ccdf2962.png'>";
    } else if ($fruites[$i] == 'banana') {
        echo "<img class='fruites' src='https://vignette.wikia.nocookie.net/feed-your-pets-roblox/images/6/69/Banana.png/revision/latest?cb=20180503075351'>";
    } else if ($fruites[$i] == 'pear') {
        echo "<img class='fruites' src='https://kopparberg.co.uk/wp-content/uploads/2018/04/Pear.png'>";
    }
}


?>

<style>
    .fruites {
        width: 70px;
    }
</style>
