<?php
namespace USA;
require_once 'mytraits.php';

class WashingtonDC{

use \MyTrait;

    public $capital;
    public function setCapital(){
        $this->capital = 'Washington. DC';
    }
    protected function giveStimulusPackage(){
        return "give $1200 dollar assistance to every tax payer adult";
    }

    protected function startWar(){
        return "Only DC can start a war";
    }


}


class NewYork extends WashingtonDC {
   public function giveStimulusPackage()
   {
       return parent::giveStimulusPackage(); // TODO: Change the autogenerated stub
   }
   public function startWar()
   {
       return parent::startWar(); // TODO: Change the autogenerated stub
   }
}


$newyork = new NewYork();

$newyork->setCapital();
echo $newyork->writingEssay();

